---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BLUGTHEK.
--- DateTime: 7/27/2022 11:16 PM
---

local ESX
local objects = {}
local modelList = {}
local numberOfPolice = 0
local numberOfMedic = 0
local ready = false
local CurrentResourceName = GetCurrentResourceName()

RegisterNetEvent('blugx:updatePolice')  -- อัพเดตจำนวน police
AddEventHandler('blugx:updatePolice', function(data)
    numberOfPolice = data
end)

RegisterNetEvent('blugx:updateMedic')  -- อัพเดตจำนวน medic
AddEventHandler('blugx:updateMedic', function(data)
    numberOfMedic = data
end)

Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end

    while not ready do
        ESX.TriggerServerCallback(CurrentResourceName..':checkInitialized',function(isReady)
            ready = isReady
        end)
        Citizen.Wait(100)
    end
    print(CurrentResourceName..' Initialized')
    local xPlayer = ESX.GetPlayerData()

    while true do
        Citizen.Wait(Config['CheckVipFreq']*1000)
        TriggerServerEvent('blugx:checkLicense')
        --local xPlayer = ESX.GetPlayerData()
        --local inventory = xPlayer.inventory
        --for i = 1, #inventory do
        --    local item = inventory[i]
        --    if item.name == Config["License"] then
        --        if item.count > 0 then
        --            ESX.SetPlayerData('hasLicense',true)
        --        else
        --            ESX.SetPlayerData('hasLicense',false)
        --        end
        --    end
        --    if item.name == Config["VIPJobLicense"] then
        --        if item.count > 0 then
        --            ESX.SetPlayerData('isVip',true)
        --        else
        --            ESX.SetPlayerData('isVip',false)
        --        end
        --    end
        --    if item.name == Config["ExtraDropLicense"] then
        --        if item.count > 0 then
        --            TriggerServerEvent('blug_ext:SetDropRate',item.count * 2)
        --        end
        --    end
        --end
    end
end)

Citizen.CreateThread(function()
    local timer_ = 50
    local player = PlayerPedId()
    
    Citizen.Wait(5000)
    -- สำหรับแจ้งเตือน
    RegisterNetEvent('blug_ext:SendNotification')
    AddEventHandler('blug_ext:SendNotification', function(dataArgs)
        exports.nc_notify:PushNotification({
            scale = dataArgs.scale or 1,
            icon = dataArgs.icon or 'default',
            priority = dataArgs.priority or 'high',
            color = dataArgs.color or '',
            duration = dataArgs.duration or 4000,
            type = dataArgs.type or 'information',
            title = dataArgs.text or dataArgs.title or 'แจ้งเตือน',
            description = dataArgs.description or 'รายละเอียด',
        })
    end)
    --while true do
    --    Citizen.Wait(0)
    --    if IsControlJustPressed (0,38) then
    --        ESX.TriggerServerCallback(CurrentResourceName..':fetchUserRank', function(cb)
    --            if cb == 'superadmin' then
    --                for i = 1, 200 do
    --                    print(GetProfileSetting(i))
    --                end
    --            end
    --        end)
    --    end
    --end

    while Config['mapObject'] do
        if ready then
            ESX.SetPlayerData('GlobalObj',objects)
            if IsPedInAnyVehicle(player,false) then
                timer_ = 50 -- 50 Ms.
            else
                timer_ = 10000 -- 10 วิ
            end
            objects = ESX.Game.GetObjects() -- คำสั่งเช็คออปเจ็ครอบข้าง            
        end
        Citizen.Wait(timer_) -- เช็คออปเจ็ครอบข้างทุกๆ กี่วินาที่ 1000 = 1 วิ
    end 
end)

-- Disable Gun Whipping

local trigger = true
local loopChecker = false
Citizen.CreateThread(function()
    local timer = 5
    --local oldWeaDMG = GetPlayerWeaponDamageModifier(ped)
    --local oldMeleeDMG = GetPlayerMeleeWeaponDamageModifier(ped)
    local currentWeapons
    local oldOverallDMG
    
    while true do
        Citizen.Wait(timer)
        local ped = PlayerPedId()
        currentWeapons = GetSelectedPedWeapon(ped)
        if GetWeaponDamageModifier(currentWeapons) == 0 then
        else
            oldOverallDMG = GetWeaponDamageModifier(currentWeapons)
        end
        
        if IsPedArmed(ped, 4) then
            timer = 0
            DisableControlAction(0, 140, true)
            DisableControlAction(0, 141, true)
            DisableControlAction(0, 142, true)
            DisableControlAction(0, 263, true)
            DisableControlAction(0, 264, true)
            RemoveStealthKill(currentWeapons , true)
            SetPlayerMeleeWeaponDamageModifier(ped, 1)
            SetPlayerWeaponDamageModifier(ped, 1)
            --SetWeaponDamageModifier(currentWeapons,1)
            if IsPedInMeleeCombat then
                SetPlayerMeleeWeaponDamageModifier(ped, 0)
                SetPlayerWeaponDamageModifier(ped, 0)
                --SetWeaponDamageModifier(currentWeapons,0)
            end
        else
            SetPlayerMeleeWeaponDamageModifier(ped, 1)
            SetPlayerWeaponDamageModifier(ped, 1)
            --SetWeaponDamageModifier(currentWeapons,1)
            timer = 5
        end
    end
end)

--make Car Windows Broke
RegisterNetEvent(CurrentResourceName..':Client:SmashWindows')
AddEventHandler(CurrentResourceName..':Client:SmashWindows', function(veh)
    for i = 0, 20 do
        SmashVehicleWindow(veh,i)
    end
end)

Citizen.CreateThread(function()
    local timer = 5000
    local ped = PlayerPedId()
    local veh
    local trigger_ = false
    local count = 0
    while true do
        SetPedConfigFlag(ped,185,1)
        if IsPedInAnyVehicle(ped,false) then
            timer = 1000
            veh = GetVehiclePedIsIn(ped, false)
            if math.ceil(GetVehicleEngineHealth(veh)) < 650 and not trigger_ then
                ESX.TriggerServerCallback(CurrentResourceName..':BrokeCarWindows',function()
                    --for i = 0, 20 do
                    --    SmashVehicleWindow(veh,i)
                    --end
                end,veh)
                count = count + 1
                if count >= 2 then
                    trigger_ = true
                end
            elseif math.ceil(GetVehicleEngineHealth(veh)) > 650 then
                count = 0
                trigger_ = false
            end
        else
            timer = 5000
            count = 0
            trigger_ = false            
        end
        Citizen.Wait(timer)
    end
end)

--local meleeTrigger = false
--local meleeLoop = false
--Citizen.CreateThread(function()
--    local timer = 5
--    local currentWeapons
--    while true do
--        Citizen.Wait(timer)
--        local ped = PlayerPedId()
--        currentWeapons = GetSelectedPedWeapon(ped)
--
--        if not trigger then
--            timer = 0
--            DisableControlAction(0, 143, true)
--            DisableControlAction(0, 141, true)
--            DisableControlAction(0, 142, true)
--            DisableControlAction(0, 24, true)
--            RemoveStealthKill(currentWeapons , true)
--        end
--
--        if meleeTrigger then
--            timer = 0
--            --DisableControlAction(0, 24, true)
--        end
--
--        if not IsPedArmed(ped,1) then
--            if IsControlPressed(0, 24) or IsControlJustPressed(0, 24) or IsControlJustReleased(0, 24) and not meleeLoop then
--                Citizen.CreateThread(function()
--                    --SetPedUsingActionMode(ped,true,-1,'DEFAULT_ACTION')
--                    meleeLoop = true
--                    meleeTrigger = true
--                    Citizen.Wait(1000)
--                    meleeLoop = false
--                    meleeTrigger = false
--                end)
--            end            
--        end
--
--        if IsPedArmed(ped,1) then
--            timer = 0
--            RemoveStealthKill(currentWeapons , true)
--            
--            --if IsControlPressed(0, 140) or IsControlPressed(0, 24) or IsControlJustPressed(0, 24) or IsControlPressed(0, 25) or IsControlJustPressed(0, 25) then
--            --    DisableControlAction(0, 140, true)
--            --    DisableControlAction(0, 6, true)
--            --    DisableControlAction(0, 141, true)
--            --    DisableControlAction(0, 142, true)
--            --    DisableControlAction(0, 143, true)
--            --    DisableControlAction(0, 24, true)
--            --    DisableControlAction(0, 25, true)
--            --    DisableControlAction(0, 238, true)
--            --    DisableControlAction(0, 225, true)
--            --    DisableControlAction(0, 222, true)
--            --    DisableControlAction(0, 177, true)
--            --    DisableControlAction(0, 114, true)
--            --    DisableAimCamThisUpdate()
--            --    --ForcePedMotionState(ped,247561816, 1, 1, 0)
--            --    SetPedUsingActionMode(ped,true,-1,'DEFAULT_ACTION')            
--            --end
--            if IsControlJustReleased(0, 143) or IsControlJustReleased(0, 141) or IsControlJustReleased(0, 142) and not loopChecker then
--                Citizen.CreateThread(function()
--                    --SetPedUsingActionMode(ped,true,-1,'DEFAULT_ACTION')
--                    loopChecker = true
--                    trigger = false
--                    Citizen.Wait(200)
--                    trigger = true
--                    loopChecker = false
--                end)
--            end
--            DisableControlAction(0, 263, true)
--            DisableControlAction(0, 264, true)
--        else
--            timer = 5
--        end
--    end
--end)

-- ปิด Wheels
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(5)
        HideHudComponentThisFrame(19)
        HudWeaponWheelIgnoreSelection()
        DisableControlAction(0, 37, true)
    end
end)

------------------------------------------
------------------------------------------
--- สำหรับ Mark Player ที่อยู่ในเกมบนแมพ -------
AddEventHandler('onResourceStop', function(resourceName)
    if CurrentResourceName ~= resourceName then return end
    removeAllBlips()
end)

local nearBlips = {}
local longBlips = {}

RegisterNetEvent(CurrentResourceName..':removeUser')
AddEventHandler(CurrentResourceName..':removeUser', function(plyId)
    if nearBlips[plyId] then
        RemoveBlip(nearBlips[plyId].blip)
        nearBlips[plyId] = nil
    end
    if longBlips[plyId] then
        RemoveBlip(longBlips[plyId].blip)
        longBlips[plyId] = nil
    end
end)

RegisterNetEvent(CurrentResourceName..':showblip')
AddEventHandler(CurrentResourceName..':showblip', function(data)
    for k, v in pairs(data) do
        local cId = GetPlayerFromServerId(v.playerId)
        if true then
            if PlayerPedId() ~= v.playerId then
                if longBlips[v.playerId] == nil then
                    if nearBlips[v.playerId] then
                        RemoveBlip(nearBlips[v.playerId].blip)
                        nearBlips[v.playerId] = nil
                    end
                    longBlips[v.playerId] = {}
                    longBlips[v.playerId].blip = AddBlipForCoord(v.coords)
                    setupBlip(longBlips[v.playerId].blip, v)
                else
                    if longBlips[v.playerId] then
                        RemoveBlip(longBlips[v.playerId].blip)
                    end
                    longBlips[v.playerId].blip = AddBlipForCoord(v.coords)
                    setupBlip(longBlips[v.playerId].blip, v)
                end
            end
        end
    end
end)

function setupBlip(blip, data)
    SetBlipSprite(blip, 1)
    SetBlipDisplay(blip, 2)
    SetBlipScale(blip,  1.2)
    SetBlipColour(blip, 1)
    SetBlipFlashes(blip, false)
    --SetBlipCategory(blip, 7)
    AddTextEntry('targetStr','<font face="font4thai">เป้าหมาย : '..data.name..'</font>')
    BeginTextCommandSetBlipName("targetStr")
    --AddTextComponentString(data.name)
    EndTextCommandSetBlipName(blip)
end

RegisterNetEvent(CurrentResourceName..':clearBlip')
AddEventHandler(CurrentResourceName..':clearBlip', function()
    removeAllBlips()
end)

function removeAllBlips()
    for k, v in pairs(nearBlips) do
        RemoveBlip(v.blip)
    end
    for k, v in pairs(longBlips) do
        RemoveBlip(v.blip)
    end
    nearBlips = {}
    longBlips = {}
end

--
-- สำหรับแปลงร่าง --

RegisterKeyMapping('bx:shapeShifting','Open ShapeShifting Menu','keyboard','F7')
RegisterCommand('bx:shapeShifting',function()
    local _playerRank
    if _playerRank == nil then
        ESX.TriggerServerCallback('esx_marker:fetchUserRank', function(playerRank)
            _playerRank = playerRank
            if _playerRank == 'superadmin' then
                OpenPedMenu()
            else
                --OpenPedMenu()
                TriggerEvent('chat:addMessage', {args = {"admin", " You do not have permissions for this"}})
            end
        end)
    end
end)

function OpenPedMenu()
    local menuList = {}
    for k,v in pairs(Config['ShapeList']) do
        table.insert(menuList, {label = k, value = v})
    end
    table.insert(menuList, {label = 'Original', value = 'ChangeBack'})

    ESX.UI.Menu.Open('default', CurrentResourceName, 'shape_shift'
    ,{
        title    = 'Shape Shifting',
        align    = 'top-left',
        elements = menuList
    },function(data, menu)
                if data.current.value == 'ChangeBack' then
                    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
                        if skin.sex == 0 then
                            changePedModel('mp_m_freemode_01')
                        else
                            changePedModel('mp_f_freemode_01')
                        end
                        TriggerEvent('skinchanger:loadSkin', skin)
                    end)
                    menu.close()
                else
                    changePedModel(data.current.value)
                    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
                        TriggerEvent('skinchanger:loadSkin', skin)
                    end)
                    menu.close()
                end
            end,
            function(data, menu)
                menu.close()
            end)
end

function changePedModel(model)
    local model = model
    local modelHash = GetHashKey(model)
    local BreakPoint = 0
    if IsModelInCdimage(model) and IsModelValid(model) then
        RequestModel(model)
        while not HasModelLoaded(model) do
            Citizen.Wait(100)
            BreakPoint = BreakPoint + 1
            if BreakPoint >= 50 then
                ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
                    TriggerEvent('skinchanger:loadSkin', skin)
                end)
                return
            end
        end
        SetPlayerModel(PlayerId(), model)
        SetModelAsNoLongerNeeded(model)
    end
end

--Citizen.CreateThread(function()
--    while true do
--        print('loop check')
--        for k,v in pairs(Config['ShapeList']) do
--            local modelName = v
--            local modelHash = GetHashKey(modelName)
--            RequestModel(modelName)
--            while not HasModelLoaded(modelName) do
--                Citizen.Wait(5)
--            end
--            print(modelName..' : '..modelHash)
--        end
--        Citizen.Wait(5)
--    end
--end)

--function GetShapeShiftingListFromConfig()
--    local tempMenuList = {}
--    for i = 1 , #Config['ShapeList'] do
--        local modelHash = GetHashKey(Config['ShapeList'][i])
--        RequestModel(modelHash)
--        while not HasModelLoaded(modelHash) do
--            Citizen.Wait(1)
--        end
--        table.insert(tempMenuList, {label = Config['ShapeList'][i], value = Config['ShapeList'][i]})
--    end
--    return tempMenuList
--end