---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 10/2/2022 3:11 PM
---

Config = {}

Config['CheckVipFreq'] = 10
Config['mapObject'] = true

Config["License"] = 'Job_license'
Config["VIPJobLicense"] = 'VIP_Job'
Config["ExtraDropLicense"] = 'X2_fram'

Config['ShapeList'] = {
    Nemesis = 'Nemesis_Big',
    SirenHead = 'Siren_Head',
    FemalePlayer = 'mp_f_freemode_01',
    MalePlayer = 'mp_m_freemode_01',
}