---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BLUGTHEK.
--- DateTime: 7/27/2022 6:56 PM
---

ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

local queue = {}

local function CopAlert(text,description, pos,ped)
	local xPlayers = ESX.GetPlayers()
	for i=1, #xPlayers, 1 do
 		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
 		if xPlayer.job.name == 'police' then
			
			TriggerClientEvent("blug_ext:SendNotification", xPlayers[i], {
				text = text,
				description = description,
				color = Config["Color"].police,
				duration = Config["duration"] * 800,
			})
			
			TriggerClientEvent("blug_ext:SendNotification", xPlayers[i], {
				text = text,
				description = 'กด <btn>Alt</btn> + <btn>1</btn> เพื่อรับงาน',
				color = Config["Color"].police,
				duration = Config["duration"] * 800,
			})
			
			TriggerClientEvent("blug_ext:alertArea", xPlayers[i], pos)
		
		end
	end
end

local function AmbulanceAlert(text, description,pos,ped)
	local xPlayers = ESX.GetPlayers()
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		if xPlayer.job.name == 'ambulance' then
			TriggerClientEvent("blug_ext:SendNotification", xPlayers[i], {
				text = text,
				description = description,
				color = Config["Color"].ambulance,
				duration = Config["duration"] * 800,
			})
			TriggerClientEvent("blug_ext:SendNotification", xPlayers[i], {
				text = text,
				description = 'กด <btn>Alt</btn> + <btn>1</btn> เพื่อรับงาน',
				color = Config["Color"].ambulance,
				duration = Config["duration"] * 800,
			})
			TriggerClientEvent("blug_ext:alertArea", xPlayers[i], pos)
		end
	end
end

RegisterServerEvent("blug_ext:accept")
AddEventHandler("blug_ext:accept", function(dataArgs)
	local xPlayers = ESX.GetPlayers()
	local name = GetPlayerName(source)
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		local textAccept = '<btn>'..name..'</btn> รับเคสแล้ว'
		if xPlayer.job.name == dataArgs.job then
			TriggerClientEvent('blug_ext:SendNotification', xPlayers[i], {
				text = dataArgs.text,
				description = textAccept,
				type = 'alert',
				color = dataArgs.color,
				timeout = dataArgs.timeout * 800,
			})
		end
	end
end)

local function InsertQueue(pos)
	local num
	for i=1, 9 do
		local v = queue[i]
		if v == nil then
			num = i
			queue[i] = {
				time = GetGameTimer() + (Config["duration"] * 800),
				pos = pos
			}
			break
		end
	end
	return num
end

RegisterServerEvent("blug_ext:getLocation")
AddEventHandler("blug_ext:getLocation", function(num,dataArgs)
	local data = queue[num]
	if data then
		TriggerClientEvent("blug_ext:sendLocation", source, data.pos,dataArgs)
	end
end)

local player_report = {}
RegisterServerEvent("blug_ext:defaultAlert")
AddEventHandler("blug_ext:defaultAlert", function(type, gender, location, pos)
	local xPlayers = ESX.GetPlayers()
	local JobCanAccept	
	local targetPlayer = source
	
	-- ท่อนนี้ใช้เช็คเวลา เลยเวลาตอบรับ จะปิดไม่ให้รับเคส
	if player_report[source] and player_report[source] > GetGameTimer() then	
		return
	end
	--print(type, gender, location, pos)
	local num = InsertQueue(pos)
	if not num then return end
	
	local action
	if type == "carjacking" then
		action = Config["translate"]["action_carjacking"]
		
	elseif type == "melee" then
		action = Config["translate"]["action_melee"]
		
	elseif type == "gunshot" then
		action = Config["translate"]["action_gunshot"]
		
	elseif type == "drug" then
		action = Config["translate"]["action_drug"]
		
	elseif type == "thief" then
		action = Config["translate"]["action_thief"]
		
	elseif type == "fishing" then
		action = Config["translate"]["action_fishing"]
		
	elseif type == "burglary" then
		action = Config["translate"]["action_burglary"]
		
	elseif type == "cement" then
		action = Config["translate"]["action_cement"]
		
	elseif type == "soft_drink" then
	    action = "'มีคนกำลังงัดตู้น้ำ"

	elseif type == "cable" then
		action = Config["translate"]["action_cable"]
		
	elseif type == "wire" then
		action = Config["translate"]["action_cable"]
		
	elseif type == "tumra" then
		action = Config["translate"]["action_tumra"]
		
	elseif type == "dead" then
		action = Config["translate"]["action_dead"]
		
	elseif type == "coma" then
		action = Config["translate"]["action_coma"]
		
	elseif type == "bodybag" then
		action = Config["translate"]["action_bodybag"]		
	else
		return
	end
	
	player_report[source] = GetGameTimer() + (Config["duration"] * 800)
	local text = 'มีคดีเกิดขึ้น'	

	if type == "coma" then
		JobCanAccept = 'ambulance'
		local ambulanceDesc = string.format("เพศ : <btn>%s</btn><p></p>ตายจากการ : %s<p></p>ตำแหน่งโดยคาดการ์ณ : <btn>%s</btn>",gender,action,location)
		AmbulanceAlert(text,ambulanceDesc, pos)
	else
		JobCanAccept = 'police'
		local description = string.format("เพศ : <btn>%s</btn><p></p>การกระทำ : %s<p></p>ตำแหน่งโดยคาดการ์ณ : <btn>%s</btn>",gender,action,location)
		CopAlert(text,description, pos)
	end

	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		if xPlayer.job.name == JobCanAccept then
			TriggerClientEvent('blug_ext:CheckJob', xPlayers[i], JobCanAccept,targetPlayer)
		end
	end
	
end)

RegisterServerEvent('blug_ext:SendNotificationTarget')
AddEventHandler('blug_ext:SendNotificationTarget', function(target,dataArgs)
	local _target = tonumber(target)
	print(_target)
	print(dataArgs.title)
	print(dataArgs.description)

	TriggerClientEvent('blug_ext:SendNotification',_target, { title = dataArgs.title,
															  description = dataArgs.description
	})
end)



Citizen.CreateThread(function()
	while true do
		for i=1, 9 do
			local v = queue[i]
			if v and v.time < GetGameTimer() then
				queue[i] = nil
			end
		end
		Citizen.Wait(500)
	end
end)