---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 9/3/2022 5:51 PM
---
local fontId = RegisterFontId('font4thai')
local CurrentResourceName = GetCurrentResourceName()
local bossModel 
local bossHash
local bossWeaponsList

local minionsCount = 0

local groupInteger = 777253
local killSwitch = false

Citizen.CreateThread(function()
    while not Config.init and Config.init ~= nil do
        Wait(1)
    end
    
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end

    while ESX.GetPlayerData().job == nil do
        Citizen.Wait(10)
    end
    
    bossModel = Config.Boss.Boss.Model
    bossWeaponsList = Config.Boss.Boss.Weapons
    bossHash = GetHashKey(bossModel)
    RequestModel(bossHash)
    while not HasModelLoaded(bossHash) do
        Citizen.Wait(1)
    end

    while not Config['init'] do
        Citizen.Wait(500)
        print('Wait for resource to be Initialized...')
        ESX.TriggerServerCallback(CurrentResourceName..':checkInitialized',function(isReady) 
            Config['init'] = isReady
        end)
    end
    print('Boss Fight Initialise')

    local timer_ = 50
    while true do
        if minionsCount > 0 then
            SetGroupFormation(groupInteger,1)
            timer_ = 5
        else
            timer_ = 50
        end
        Citizen.Wait(timer_)
    end
end)

local playerDatabase = {}
local bossReady = false
local theHeroesIsMe = false
local bossPed

function CreateBoss(coord)
    bossReady = false
    bossPed = CreatePed(4,bossModel,coord.x,coord.y,coord.z+1, 10, true, true)
    FreezeEntityPosition(bossPed,1)
    SetEntityInvincible(bossPed,1)
    TriggerEvent(CurrentResourceName..':updateBossPed',bossPed)

    while not bossReady do
        Citizen.Wait(100)
        ESX.TriggerServerCallback(CurrentResourceName..':createServerBoss',function(callback)
            if callback.bPed == bossPed then
            bossReady = true
            end
            if bossReady then
                print('Boss Has Been Create')
                if callback.mainChar == true then
                    theHeroesIsMe = true
                end
            end
        end,bossPed)
    end

    --Citizen.CreateThread(function()
    --    local bossPhase = {}
    --    local healthPhase = {}
    --    local minionsList = {}
    --    if configBoss.BossHasPhase >= 0 and type(configBoss.BossHasPhase) == 'number' then
    --        local health_ = GetEntityHealth(bossPed)
    --        local subtract = health_ / configBoss.BossHasPhase
    --        for i = 1, configBoss.BossHasPhase - 1 do
    --            health_ = health_ - subtract
    --            table.insert(bossPhase,true)
    --            table.insert(healthPhase,health_)
    --        end
    --        for k in pairs(Config['Minions']) do
    --            table.insert(minionsList,k)
    --        end
    --        table.sort(minionsList)
    --    end
    --
    --    Citizen.Wait(500)
    --    TaskCombatHatedTargetsAroundPed(bossPed,10,0)
    --    local lastThread = false
    --
    --    --region Main Boss loop
    --    while bossPhase ~= nil and bossReady do
    --        if bossPhase ~= nil then
    --            for i = 1, #bossPhase do
    --                while bossPhase[i] == true do
    --                    local getHealth = GetEntityHealth(bossPed)
    --                    local health = math.floor(healthPhase[i] + 50)
    --                    if killSwitch then
    --                        SetEntityHealth(bossPed,0)
    --                        bossPhase[i] = false
    --                        --Citizen.Wait(2500)
    --                        --killSwitch = false
    --                        --DeleteEntity(bossPed)
    --                        --bossPhase = {}
    --                        --healthPhase = {}
    --                        --minionsList = {}
    --                        break
    --                    elseif not IsPedDeadOrDying(bossPed) then
    --                        if getHealth >= healthPhase[i] and minionsCount >= 1 then
    --                            FreezeEntityPosition(bossPed,1)
    --                            SetEntityInvincible(bossPed,1)
    --                        elseif getHealth >= healthPhase[i] then
    --                            if not switch then
    --                                FreezeEntityPosition(bossPed,0)
    --                                SetEntityInvincible(bossPed,0)
    --                                switch = true
    --                                print(getHealth..' isGetHealth')
    --                                print(health..' is current')
    --                                print('bossloop..'..i)
    --                            end
    --                        elseif getHealth < healthPhase[i] then
    --                            if bossPhase[i] == true then
    --                                bossPhase[i] = false
    --                                if switch then
    --                                    switch = false
    --                                    SetEntityHealth(bossPed,health)
    --                                end
    --                                TriggerEvent(CurrentResourceName..':CreateMinion',GetEntityCoords(bossPed),minionsList[i],bossPed)
    --                                bossSetupWeaponByList(bossPed,configBoss.UseWeapon,bossWeaponsList,i + 1)
    --                            end
    --                            bossPhase[i] = false
    --                        end
    --                    elseif IsPedDeadOrDying(bossPed) then
    --                        --DeleteEntity(bossPed)
    --                        bossPhase[i] = false
    --                    end
    --                    Citizen.Wait(0)
    --                end
    --                Citizen.Wait(0)
    --            end
    --            if not lastThread and not IsPedDeadOrDying(bossPed) then
    --                lastThread = true
    --                SetEntityHealth(bossPed,500)
    --            end
    --            if killSwitch then
    --                SetEntityHealth(bossPed,0)
    --                --Citizen.Wait(2500)
    --                --killSwitch = false
    --                --DeleteEntity(bossPed)
    --                --bossPhase = {}
    --                --healthPhase = {}
    --                --minionsList = {}
    --            end
    --            if minionsCount >= 1 then
    --                FreezeEntityPosition(bossPed,1)
    --                SetEntityInvincible(bossPed,1)
    --            else
    --                FreezeEntityPosition(bossPed,0)
    --                SetEntityInvincible(bossPed,0)
    --            end
    --            Citizen.Wait(0)
    --        end
    --        if IsPedDeadOrDying(bossPed) then
    --            Citizen.Wait(2000)
    --            killSwitch = false
    --            DeleteEntity(bossPed)
    --            bossPhase = {}
    --            healthPhase = {}
    --            minionsList = {}
    --            if bossReady then
    --                bossReady = false
    --                TriggerServerEvent(CurrentResourceName..':server:RefreshPlayer')
    --            end
    --        end
    --        Citizen.Wait(0)
    --    end
    --
    --    print('Boss Has Died')
    --    --endregion
    --end)
end

local bossPhase = {}
local healthPhase = {}
local minionsList = {}
local lastThread = false
local switch = false

function CreateBossLoop()
    local configBoss = Config.Boss.Boss
    if configBoss.BossHasPhase >= 0 and type(configBoss.BossHasPhase) == 'number' then
        local health_ = GetEntityHealth(bossPed)
        local subtract = health_ / configBoss.BossHasPhase
        for i = 1, configBoss.BossHasPhase - 1 do
            health_ = health_ - subtract
            table.insert(bossPhase,true)
            table.insert(healthPhase,health_)
        end
        for k in pairs(Config['Minions']) do
            table.insert(minionsList,k)
        end
        table.sort(minionsList)
    end
end

--region Main Boss loop
Citizen.CreateThread(function()
    local configBoss = Config.Boss.Boss
    while true do
        if theHeroesIsMe == false then
            return
        end
        if bossPhase ~= nil and bossPed ~= nil and bossReady then
            FreezeEntityPosition(bossPed,1)
            SetEntityInvincible(bossPed,1)
            Citizen.Wait(500)
            TaskCombatHatedTargetsAroundPed(bossPed,10,0)
            Citizen.Wait(1000)
            FreezeEntityPosition(bossPed,0)
            SetEntityInvincible(bossPed,0)
            for i = 1, #bossPhase do
                while bossPhase[i] == true do
                    local getHealth = GetEntityHealth(bossPed)
                    local health = math.floor(healthPhase[i] + 50)
                    if killSwitch then
                        SetEntityHealth(bossPed,0)
                        bossPhase[i] = false
                        --Citizen.Wait(2500)
                        --killSwitch = false
                        --DeleteEntity(bossPed)
                        --bossPhase = {}
                        --healthPhase = {}
                        --minionsList = {}
                        break
                    elseif not IsPedDeadOrDying(bossPed) then
                        if getHealth >= healthPhase[i] and minionsCount >= 1 then
                            FreezeEntityPosition(bossPed,1)
                            SetEntityInvincible(bossPed,1)
                        elseif getHealth >= healthPhase[i] then
                            if not switch then
                                FreezeEntityPosition(bossPed,0)
                                SetEntityInvincible(bossPed,0)
                                switch = true
                                print(getHealth..' isGetHealth')
                                print(health..' is current')
                                print('bossloop..'..i)
                            end
                        elseif getHealth < healthPhase[i] then
                            if bossPhase[i] == true then
                                bossPhase[i] = false
                                if switch then
                                    switch = false
                                    SetEntityHealth(bossPed,health)
                                end
                                TriggerEvent(CurrentResourceName..':CreateMinion',GetEntityCoords(bossPed),minionsList[i],bossPed)
                                bossSetupWeaponByList(bossPed,configBoss.UseWeapon,bossWeaponsList,i + 1)
                            end
                            bossPhase[i] = false
                        end
                    elseif IsPedDeadOrDying(bossPed) then
                        --DeleteEntity(bossPed)
                        bossPhase[i] = false
                    end
                    Citizen.Wait(0)
                end
                Citizen.Wait(0)
            end
            if not lastThread and not IsPedDeadOrDying(bossPed) then
                lastThread = true
                SetEntityHealth(bossPed,500)
            end
            if killSwitch then
                SetEntityHealth(bossPed,0)
                Citizen.Wait(2500)
                killSwitch = false
                DeleteEntity(bossPed)
                bossPhase = {}
                healthPhase = {}
                minionsList = {}
                bossReady = false
                bossPed = nil
                TriggerServerEvent(CurrentResourceName..':server:RefreshPlayer')
            end
            if minionsCount >= 1 then
                FreezeEntityPosition(bossPed,1)
                SetEntityInvincible(bossPed,1)
            else
                FreezeEntityPosition(bossPed,0)
                SetEntityInvincible(bossPed,0)
            end
            Citizen.Wait(0)
        elseif IsPedDeadOrDying(bossPed) and bossPed ~= nil  then
            Citizen.Wait(2000)
            killSwitch = false
            DeleteEntity(bossPed)
            bossPhase = {}
            healthPhase = {}
            minionsList = {}
            if bossReady then
                bossReady = false
                bossPed = nil
                TriggerServerEvent(CurrentResourceName..':server:RefreshPlayer')
            end
        end
        Citizen.Wait(0)
    end

    print('Boss Has Died')
end)
--endregion

--region Boss Set to be group leader
function SetBossToBeGroupLeader(xPed)
   local targetPed = xPed
    SetPedAsGroupMember(targetPed, groupInteger)
    Citizen.Wait(100)
    SetPedAsGroupLeader(targetPed, groupInteger)
end

function bossSetupWeaponByList(xPed,isUsingWeapons,WeaponsList,index)
    if Config.Boss.Boss.RandomWeapon then
        local maxRange = tableLength(WeaponsList)
        SetupWeapon(xPed,isUsingWeapons,WeaponsList[math.random(1,maxRange)])
    else
        SetupWeapon(xPed,isUsingWeapons,WeaponsList[index])
    end
end
--endregion

--region Minions
AddEventHandler(CurrentResourceName..':CreateMinion',function(bossCoord,minion_,bossPed)
    CreateMinion(bossCoord,minion_,bossPed)
end)

function CreateMinion(bossCoord,minion_,bossPed)
    local minion
    local minionConfig = Config['Minions'][minion_]
    local minionModel = minionConfig.Model
    local spawnRadius = math.floor(Config['radius'] / 4 ) 

    minionsCount = 0
    
    RequestModel(GetHashKey(minionModel))
    while not HasModelLoaded(GetHashKey(minionModel)) do
        Wait(1)
    end
    for i = 1, Config['HowManyMinions'] do
        local tempX = bossCoord.x + math.random(1,spawnRadius)
        local tempY = bossCoord.y + math.random(1,spawnRadius)
        minion = CreatePed(4,minionModel,tempX,tempY,bossCoord.z+1, 10, true, true)
        SetRelationshipGroupToPed(minion)
        SetAttributesToPedByPed(minion,minionConfig.Health,minionConfig.WeaponAccuracy)
        SetDefensiveArea(minion,bossPed)
        SetupWeapon(minion,minionConfig.UseWeapon,minionConfig.Weapon)
        SetPedAsGroupMember(minion, groupInteger)
        CreateMinionLoop(minion,i)
    end
end

function CreateMinionLoop(xPed,index)
    local thisMinion = xPed
    local thisIndex = index
    minionsCount = minionsCount + 1
    TaskTurnPedToFaceEntity(thisMinion,PlayerPedId(),-1)
    TaskTurnPedToFaceEntity(thisMinion,PlayerPedId(),-1)

    Citizen.CreateThread(function()
        Citizen.Wait(100)
        TaskCombatPed(thisMinion,PlayerPedId(),0,16)
        Citizen.Wait(100)
        TaskCombatHatedTargetsAroundPed(thisMinion,10,0)
        SetGroupFormation(groupInteger,1)
        while not IsPedDeadOrDying(thisMinion) do
            if killSwitch then
                SetEntityHealth(thisMinion,0)
                Citizen.Wait(2500)
                killSwitch = false
                break
            end
            Citizen.Wait(1000)
        end
        minionsCount = minionsCount - 1
        DropItemBox(GetEntityCoords(thisMinion))
        print(minionsCount)
        Citizen.Wait(1000)

        DeleteEntity(thisMinion)
    end)
end
--endregion

--region Boss and minion setup
function SetupWeapon(xPed,isUseWeapon,weapon)
    if IsPedArmed(xPed,1) or IsPedArmed(xPed,4) then
        RemoveAllPedWeapons(xPed,1)
    end
    if isUseWeapon then
        local Weapons_ = GetHashKey(weapon)
        GiveWeaponToPed(xPed,Weapons_,1,true,false)
        SetPedInfiniteAmmo(xPed,true,Weapons_)
        SetCurrentPedWeapon(xPed,Weapons_,1)
    end
end

function SetRelationshipGroupToPed(xPed)
    SetPedRelationshipGroupHash(xPed, GetHashKey('HATES_PLAYER'))
    SetEntityOnlyDamagedByRelationshipGroup(xPed,1, GetHashKey('PLAYER'))
end

function SetAttributesToPedByPed(xPed,setHealth,pedAccuracy)
    SetPedCanRagdoll(xPed,0)
    SetPedCanRagdollFromPlayerImpact(xPed,0)

    SetPedConfigFlag(xPed,2,1)
    SetPedConfigFlag(xPed,7,1)
    SetPedConfigFlag(xPed,13,1)
    SetPedConfigFlag(xPed,33,0)
    SetPedConfigFlag(xPed,69,0)
    SetPedConfigFlag(xPed,70,0)
    SetPedConfigFlag(xPed,128,0)
    SetPedConfigFlag(xPed,140,0)
    SetPedConfigFlag(xPed,456,0)
    
    SetPedSeeingRange(xPed, 100.0)
    SetPedHearingRange(xPed, 80.0)
    SetPedCombatAttributes(xPed, 46, 1)
    SetPedFleeAttributes(xPed, 0, 0)
    SetPedCombatRange(xPed,1)
    SetPedCombatAbility(xPed,2)
    SetPedCombatMovement(xPed,2)
    SetPedAccuracy(xPed,pedAccuracy or 500)
    --SetPedFiringPattern(xPed,0xA018DB8A)
    SetPedShootRate(xPed,1000)
    SetEntityHealth(xPed,setHealth or 300)
    SetPedAsEnemy(xPed,true)
    SetPedAlertness(xPed, 3)
    SetPedSuffersCriticalHits(xPed,0)
    --SetRelationshipBetweenGroups(5,GetHashKey("PLAYER"),bossHash)
    --SetRelationshipBetweenGroups(5,bossHash,GetHashKey("PLAYER"))
end

function SetDefensiveArea(xPed,tPed)
    if tPed ~= nil then
        SetPedDefensiveAreaAttachedToPed(xPed,tPed,0,0,0,0,0,0,0,1,true)
    else
        SetPedDefensiveAreaAttachedToPed(xPed,PlayerPedId(),0,0,0,0,0,0,0,1,true)
    end
end
--endregion

--region PowerUp Box
local powerUpBoxLocation = {}
function DropItemBox(coord)
    TriggerServerEvent(CurrentResourceName..':server:addPowerUpBossLocation',coord)
end

CreateThread(function()
    local timer_ = 100
    while true do
        local ped = PlayerPedId()
        local xPlayerCoords = GetEntityCoords(ped)
        if powerUpBoxLocation == not nil then
            timer_ = 0
            for _,location in pairs(powerUpBoxLocation) do
                print(location)
                if GetDistanceBetweenCoords(xPlayerCoords, location, true) < 20 then
                        Draw3DText('ไอเท็มตรงอยู่ตรงนี้' , location.x, location.y, location.z + 1.0, 0.1,0.1)
                else
                end
            end
        else
            timer_ = 100
        end
        Citizen.Wait(timer_)
    end
end)
--endregion

--region Event
RegisterNetEvent(CurrentResourceName..':updateBossPed')
AddEventHandler(CurrentResourceName..':updateBossPed', function(bPed)
    bossPed = bPed
    local configBoss = Config.Boss.Boss

    SetRelationshipGroupToPed(bossPed)
    SetAttributesToPedByPed(bossPed,configBoss.Health,configBoss.WeaponAccuracy)
    SetDefensiveArea(bossPed)
    bossSetupWeaponByList(bossPed,configBoss.UseWeapon,bossWeaponsList,1)
    SetBossToBeGroupLeader(bossPed)
    CreateBossLoop()

    bossReady = true
end)

RegisterNetEvent(CurrentResourceName..':killBoss')
AddEventHandler(CurrentResourceName..':killBoss', function()
    killSwitch = true
end)

RegisterNetEvent(CurrentResourceName..':UpdatePlayerDatabase')
AddEventHandler(CurrentResourceName..':UpdatePlayerDatabase', function(playerFromServer)
    print('Player Has been Update')
    playerDatabase = {}
    playerDatabase = playerFromServer
    for k,v in pairs(playerDatabase) do
        print(k)
        print(v)
    end
end)

RegisterNetEvent(CurrentResourceName..':updateLootBossCoord')
AddEventHandler(CurrentResourceName..':updateLootBossCoord', function(powerUpFromServer)
    print('Loot has been update')
    powerUpBoxLocation = {}
    powerUpBoxLocation = powerUpFromServer
end)
--endregion

--region Player loop
--- Make Floating Marker
Citizen.CreateThread(function()
    local timer_ = 1000 -- 10 วิ
    while true do
        local ped = PlayerPedId()
        local xPlayerCoords = GetEntityCoords(ped)
        if playerDatabase ~= nil then
            timer_ = 0
            for k,v in pairs(playerDatabase) do
                local tPlayerPed = GetPlayerPed(GetPlayerFromServerId(k))
                if tPlayerPed ~= ped then
                    if v.hasExit == false then
                        local coords = GetEntityCoords(tPlayerPed)
                        if GetDistanceBetweenCoords(xPlayerCoords, coords, true) < 20 then
                            if v.mainCharacter == true and tPlayerPed ~= ped then
                                Draw3DText('ปกป้องฉันด้วย' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                            else
                                Draw3DText('นักสู้บอส' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                            end
                        else
                        end
                    else
                    end
                elseif tPlayerPed == ped and v.hasExit == false then
                    local coords = GetEntityCoords(ped)
                    if v.mainCharacter == true and tPlayerPed == ped then
                        Draw3DText('ปกป้องฉันด้วย' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                    else
                        Draw3DText('นักสู้บอส' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                    end
                end
            end
        else
            timer_ = 1000
        end
        Citizen.Wait(timer_)
    end
end)

---Check if main Character died
Citizen.CreateThread(function()
    local timer_ = 10000
    local trigger = false
    while true do
        local ped = PlayerPedId()
        local xPlayerCoords = GetEntityCoords(ped)
        if playerDatabase ~= nil then
            timer_ = 0
            for k,v in pairs(playerDatabase) do
                local tPlayerPed = GetPlayerPed(GetPlayerFromServerId(k))
                if tPlayerPed ~= ped then
                    if v.hasExit == false then
                        local coords = GetEntityCoords(tPlayerPed)
                        if GetDistanceBetweenCoords(xPlayerCoords, coords, true) < 20 then
                            if v.mainCharacter == true then
                                Draw3DText('ปกป้องฉันด้วย' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                            else
                                Draw3DText('นักสู้บอส' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                            end
                        else
                        end
                    else
                    end
                elseif tPlayerPed == ped and v.hasExit == false then
                    local coords = GetEntityCoords(ped)
                    if v.mainCharacter == true then
                        Draw3DText('ปกป้องฉันด้วย' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                    else
                        Draw3DText('นักสู้บอส' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                    end
                end
            end
        else
            timer_ = 1000
        end
        Citizen.Wait(timer_)
    end
end)

--- Check if in range of Boss
Citizen.CreateThread(function()
    local timer_ = 10000
    local trigger = false
    while true do
        if bossPed ~= nil and not IsPedDeadOrDying(bossPed) then
            timer_ = 100
            local ped = PlayerPedId()
            local xPlayerCoords = GetEntityCoords(ped)
            local coords = GetEntityCoords(bossPed)
            if GetDistanceBetweenCoords(xPlayerCoords, coords, true) < 30 then
                if not trigger then
                    print('in Range')
                    trigger = true
                    TriggerServerEvent(CurrentResourceName .. ':server:AddPlayer')
                end
            else
                if trigger and playerDatabase[source]['hasExit'] == false then
                    trigger = false
                    TriggerServerEvent(CurrentResourceName .. ':server:PlayerExit')
                end
            end
        else
            timer_ = 1000
        end
        Citizen.Wait(timer_)
    end
end)

--endregion

--region Command Ctrl
local currentWeapons_
RegisterKeyMapping('createBoss','Create Boss Test','keyboard','M')
RegisterCommand('createBoss',function()
    Citizen.Wait(300)
    local _playerRank
    local ped = PlayerPedId()
    if _playerRank == nil  then
        ESX.TriggerServerCallback("esx_marker:fetchUserRank", function(playerRank)
            _playerRank = playerRank
            if _playerRank == 'superadmin' and Config['init'] then
                local coords = GetEntityCoords(ped)
                CreateBoss(coords)
                currentWeapons_ = GetSelectedPedWeapon(ped)
                SetPedInfiniteAmmo(ped,true,currentWeapons_)
                SetCurrentPedWeapon(ped,currentWeapons_,1)
                --TriggerServerEvent(GetCurrentResourceName()..":CreateBoss",coords)
            else
                TriggerEvent('chat:addMessage', {args = {"admin", " You do not have permissions for this"}})
            end
        end)        
    end
end)

RegisterKeyMapping('killAll','Kill Boss Test','keyboard','N')
RegisterCommand('killAll',function()
    Citizen.Wait(300)
    local _playerRank
    local ped = PlayerPedId()
    if _playerRank == nil  then
        ESX.TriggerServerCallback("esx_marker:fetchUserRank", function(playerRank)
            _playerRank = playerRank
            if _playerRank == 'superadmin' then
                TriggerEvent(CurrentResourceName..':killBoss')
                currentWeapons_ = GetSelectedPedWeapon(ped)
                SetPedInfiniteAmmo(ped,true,currentWeapons_)
                SetCurrentPedWeapon(ped,currentWeapons_,1)
            end
        end)
    end
end)
--endregion

------------------------
-- Utility

function tableLength(T)
    local count = 0
    for _ in pairs(T) do count = count + 1 end
    return count
end

RegisterNetEvent(CurrentResourceName..':initialise')
AddEventHandler(CurrentResourceName..':initialise', function()
    Config['init'] = true
end)

DrawText2D = function (x, y, scale, width, height, text, r, g, b, a, outline)
    SetTextFont(fontId)
    SetTextProportional(0)
    SetTextScale(scale, scale)
    SetTextColour(r, g, b, a)
    SetTextDropShadow(0, 0, 0, 0,255)
    SetTextEdge(0, 0, 0, 0, 255)
    SetTextDropShadow()
    SetTextOutline()
    SetTextCentre(1)
    SetTextEntry("STRING")
    AddTextComponentString(text)
    DrawText(x - width/2.3, y - height/2 + 0.005)
end

function Draw3DText(textInput,x,y,z,xo,textscale)
    local x_ = x
    local y_ = y
    local z_ = z
    local px, py, pz = table.unpack(GetGameplayCamCoords())
    local dist       = GetDistanceBetweenCoords(px, py, pz, x_, y_, z_, 1)
    local scale_      = (1 / dist) * 20
    local fov        = (1 / GetGameplayCamFov()) * 100
    local scale      = scale_ * fov
    SetTextScale(textscale * scale, textscale * scale)
    SetTextFont(fontId)
    SetTextProportional(1)
    SetTextColour(250, 250, 250, 255)
    SetTextDropshadow(1, 1, 1, 1, 255)
    SetTextEdge(2, 0, 0, 0, 150)
    SetTextDropShadow()
    SetTextOutline()
    SetTextEntry("STRING")
    SetTextCentre(1)
    AddTextComponentString(textInput)
    SetDrawOrigin(x, y, z, 0)
    DrawText(0.0, 0.0)
    ClearDrawOrigin()
end

ShowToolTip = function (msg, x,y,z)
    AddTextEntry('powerUpBox', msg)
    SetFloatingHelpTextWorldPosition(1, x,y,z)
    SetFloatingHelpTextStyle(1, 1, 2, -1, 3, 0)
    BeginTextCommandDisplayHelp('powerUpBox')
    EndTextCommandDisplayHelp(2, false, false, -1)
end