---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 9/3/2022 5:55 PM
---
Config = {} or Config

Config['radius'] = 70

Config['Boss'] = {
    Boss = {
        Model = 'Nemesis_Big', -- Model NPC
        Health = 1000,
        BossHasPhase = 5,
        UseWeapon = true,
        RandomWeapon = false,
        Weapons = {
            'WEAPON_BAT',
            'WEAPON_SWITCHBLADE',
            'WEAPON_DBSHOTGUN',
            'WEAPON_AUTOSHOTGUN',
            'WEAPON_CARBINERIFLE',
        },
        WeaponAccuracy = 1000,
        WeaponDMGMultiply = 10, -- 1 คือเริ่มต้น
    }
}

Config['HowManyMinions'] = 5

Config['Minions'] = {
    minionA = {
        Model   = 'Siren_Head', -- Model NPC
        Health = 300,
        UseWeapon = true,
        Weapon = 'WEAPON_AUTOSHOTGUN',
        WeaponAccuracy = 500,
    },
    minionB = {
        Model   = 'Siren_Head', -- Model NPC
        Health = 300,
        UseWeapon = true,
        Weapon = 'WEAPON_AUTOSHOTGUN',
        WeaponAccuracy = 500,
    },
    minionC = {
        Model   = 'Siren_Head', -- Model NPC
        Health = 300,
        UseWeapon = true,
        Weapon = 'WEAPON_AUTOSHOTGUN',
        WeaponAccuracy = 500,
    },
    minionD = {
        Model   = 'Siren_Head', -- Model NPC
        Health = 300,
        UseWeapon = true,
        Weapon = 'WEAPON_AUTOSHOTGUN',
        WeaponAccuracy = 500,
    },
}