---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 9/3/2022 5:51 PM
---
local currentScriptName = GetCurrentResourceName()
local onAFKFarming = false
local _trigger = true
local init = false
local using = false
local fontId = RegisterFontId('font4thai')
local markerList_ = {}
local restrictedJob = false
local xPlayer

Citizen.CreateThread(function()
    local timer = 1000
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end

    while not init do
        Citizen.Wait(100)
        print('Wait for resource to be Initialized...')
        ESX.TriggerServerCallback(currentScriptName..':checkInitialized',function(isReady)
            init = isReady
        end)
        if init then
            print(currentScriptName..' is Ready')
            xPlayer = ESX.GetPlayerData()
            if xPlayer['isVip'] == true then
                print('Please Enjoy your VIP Benefit')
            end
            for k,v in pairs(Config['BlackListJobs']) do
                if v == xPlayer.job.name then
                    restrictedJob = true
                    break
                end
            end
        end
    end
end)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(playerData)
    xPlayer = playerData
end)

RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
    xPlayer = ESX.GetPlayerData()
    xPlayer.job = job
    for k,v in pairs(Config['BlackListJobs']) do
        if v == xPlayer.job.name then
            restrictedJob = true
            break
        end
        restrictedJob = false
    end
end)

RegisterNetEvent(currentScriptName..':useAfkItem')
AddEventHandler(currentScriptName..':useAfkItem', function(useWhat,data)
    Citizen.Wait(300)
    local ped = PlayerPedId()
    if not restrictedJob then
        if IsPedOnFoot(ped) then
            if not using then
                using = true
                TriggerServerEvent('esx:removeInventoryItem', 'item_standard', useWhat, 1)
                TriggerServerEvent(currentScriptName..':server:addMarker')
                SetPlayerHealthStatic()
                local jobConfig = data
                AutoAwayFromKeyboardFarm(jobConfig)
            else
                onAFKFarming = false
                using = false
            end
        else
            TriggerEvent("blug_ext:SendNotification",{
                description = 'ต้องยืนอยู่กับที่',
                type = 'error'
            })
        end
    else
        TriggerEvent("blug_ext:SendNotification",{
            description = 'ออกจากงานก่อนนะครับ',
            type = 'error'
        })        
    end
end)

function AutoAwayFromKeyboardFarm(jobConfig)
    onAFKFarming = true
    _trigger = true
    
    while true do
        local waitTimer = jobConfig.timer * 1000
        if xPlayer['isVip'] == true then
            waitTimer = waitTimer / 2
        end
        if onAFKFarming and _trigger then
            _trigger = false
            local playerPed = PlayerPedId()
            TaskStartScenarioInPlace(playerPed, 'WORLD_HUMAN_JOG_STANDING', 0, false)
            Citizen.Wait(waitTimer)
            if onAFKFarming then
                TriggerServerEvent(currentScriptName .. ':server:addItem' , jobConfig.items)
            else
                _trigger = true
                TriggerServerEvent(currentScriptName .. ':server:removeMarker')
                markerList_ = {}
                break             
            end
        else
            ClearPedTasksImmediately(GetPlayerPed(-1))
            break
        end
        Citizen.Wait(50)
        _trigger = true
        ClearPedTasksImmediately(GetPlayerPed(-1))
    end
    _trigger = true
    TriggerServerEvent(currentScriptName .. ':server:removeMarker')
    markerList_ = {}
end

local hunger,thirst
local lHunger,lThirst
function SetPlayerHealthStatic()
    if hunger ~= nil then
        lHunger = hunger
    else
        lHunger = 5000
    end
    if thirst ~= nil then
        lThirst = thirst
    else
        lThirst = 5000
    end
end

RegisterNetEvent('blug_ext:UpdateNeedsESX')
AddEventHandler('blug_ext:UpdateNeedsESX', function(status)
    for i = 1, #status do
        if status[i].name == 'hunger' then
            hunger = status[i].val
        elseif status[i].name == 'thirst' then
            thirst = status[i].val
        end
    end
end)

RegisterNetEvent(currentScriptName .. ':client:updateMarker')
AddEventHandler(currentScriptName .. ':client:updateMarker', function(markerList)
    markerList_ = {}
    markerList_ = markerList
end)

Citizen.CreateThread(function()
    local timer_ = 0
    while true do
        Citizen.Wait(timer_)
        local ped = PlayerPedId()
        local xPlayerCoords = GetEntityCoords(ped)
        if markerList_ ~= nil then
            for k,v in pairs(markerList_) do
                local tPlayerPed = GetPlayerPed(GetPlayerFromServerId(k))
                if tPlayerPed ~= ped then
                    if v == true then
                        local coords = GetEntityCoords(tPlayerPed)
                        if GetDistanceBetweenCoords(xPlayerCoords, coords, true) < 20 then
                            Draw3DText('AFK อยู่ค้าบ' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                        else
                        end
                    else
                    end
                elseif tPlayerPed == ped and v == true and using then
                    local coords = GetEntityCoords(ped)
                    Draw3DText('AFK อยู่ค้าบ' , coords.x, coords.y, coords.z + 1.0, 0.1,0.1)
                end
            end
        end
    end    
end)

Citizen.CreateThread(function()
    local timer_ = 0
    while true do
        Citizen.Wait(timer_)
        if using then
            timer_ = 0
            FreezeEntityPosition(PlayerPedId(),1)
            SetEntityInvincible(PlayerPedId(),1)
            for k,v in ipairs(Config['DisableKeys'])do
                DisableControlAction(0,v,true)
            end
            DrawText2D(0.93, 1.38, 0.6, 1.0, 1.0, "กด ~r~E~w~ ยกเลิก", 255, 255, 255, 255)
            if IsControlJustPressed (0,38) then
                FreezeEntityPosition(PlayerPedId(),0)
                SetEntityInvincible(PlayerPedId(),0)
                onAFKFarming = false
                using = false
                Citizen.Wait(1000)
                ClearPedTasks(PlayerPedId())
                _trigger = true
                TriggerServerEvent(currentScriptName .. ':server:removeMarker')
                markerList_ = {}
            end
        else
            timer_ = 1000
            using = false
        end
    end
end)

Citizen.CreateThread(function()
    local timer_ = 10000
    while not init do
        Citizen.Wait(100)
    end
    while hunger == nil or thirst == nil do
        Citizen.Wait(100)
        print(currentScriptName..' ...Wait for status to Update')
        Citizen.Wait(8000)
    end
    lHunger = hunger
    lThirst = thirst
    print('your status is now Up to date')
    local hg = tonumber(lHunger)
    local tr = tonumber(lThirst)
    
    while true do
        Citizen.Wait(timer_)
        if onAFKFarming then
            local ped = PlayerPedId()
            local health = GetEntityHealth(ped)
            hg = hg + 10000
            tr = tr + 10000
            if hg >= 1100000 then
                hg = 1100000
            end
            if tr >= 1100000 then
                tr = 1100000
            end
            if health >= 210 then
                health = 210
            end
            TriggerEvent('esx_status:set', 'hunger', hg)
            TriggerEvent('esx_status:set', 'thirst', tr)
            SetEntityHealth(ped, health + 2)
        else
            xPlayer = ESX.GetPlayerData()
            hg = tonumber(hunger)
            tr = tonumber(thirst)
        end
    end
end)

DrawText2D = function (x, y, scale, width, height, text, r, g, b, a, outline)
    SetTextFont(fontId)
    SetTextProportional(0)
    SetTextScale(scale, scale)
    SetTextColour(r, g, b, a)
    SetTextDropShadow(0, 0, 0, 0,255)
    SetTextEdge(0, 0, 0, 0, 255)
    SetTextDropShadow()
    SetTextOutline()
    SetTextCentre(1)
    SetTextEntry("STRING")
    AddTextComponentString(text)
    DrawText(x - width/2.3, y - height/2 + 0.005)
end

function Draw3DText(textInput,x,y,z,xo,textscale)
    local x = x
    local y = y
    local z = z
    local px, py, pz = table.unpack(GetGameplayCamCoords())
    local dist       = GetDistanceBetweenCoords(px, py, pz, x, y, z, 1)
    local scale      = (1 / dist) * 20
    local fov        = (1 / GetGameplayCamFov()) * 100
    local scale      = scale * fov
    SetTextScale(textscale * scale, textscale * scale)
    SetTextFont(fontId)
    SetTextProportional(1)
    SetTextColour(250, 250, 250, 255)
    SetTextDropshadow(1, 1, 1, 1, 255)
    SetTextEdge(2, 0, 0, 0, 150)
    SetTextDropShadow()
    SetTextOutline()
    SetTextEntry("STRING")
    SetTextCentre(1)
    AddTextComponentString(textInput)
    SetDrawOrigin(x, y, z, 0)
    DrawText(0.0, 0.0)
    ClearDrawOrigin()
end