---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 9/3/2022 5:55 PM
---
Config = {} or Config

Config['DisableKeys'] = {                        --  ปิด Keys ที่จะไม่ให้ใช้งานระหว่างโพร
    24,   -- INPUT_ATTACK
    25,   -- INPUT_AIM
    140,  -- ATTACK (R)
    21,   -- INPUT_SPRINT
    22,   -- INPUT_JUMP
    -- 38,   -- INPUT_PICKUP (E)
    29,   -- (B)
    73,   -- (X)
    323,  -- (X)
    245,  -- (T)
    246,  -- (Y)
    170,  -- (F3)
}
Config['BlackListJobs'] = {
    'police',
    'ambulance',
}
Config['maxChance'] = 100
Config['itemList'] =
{
    AFK_Card = -- ชื่อไอเท็มที่เอาไว้กดใช้ ห้ามซ้ำ
    {
        timer =  50, -- ระยะเวลา เป็น วินาที ใช้เป็นนาทีต้อง * 60
        items = {
            item = { -- ของที่ได้แน่ๆ
                {
                    chance = 100, -- โอกาสได้ จาก MaxChance
                    name = 'AFK1', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 80,
                    name = 'AFK2', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
            },

            luckyItem = { -- ของ ที่มีโอกาสได้จาก lucky

                {
                    chance = 50, -- โอกาสที่จะได้
                    name = 'mat1_tire', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 30, -- โอกาสที่จะได้
                    name = 'mat1_engine', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 46, -- โอกาสที่จะได้
                    name = 'mat1_brake', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 35, -- โอกาสที่จะได้
                    name = 'mat1_door', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 30, -- โอกาสที่จะได้
                    name = 'mat1_frame', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 20, -- โอกาสที่จะได้
                    name = 'AFK_coin', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
            },
        },
    },
    Gang = -- ชื่อไอเท็มที่เอาไว้กดใช้ ห้ามซ้ำ
    {
        timer =  1800, -- ระยะเวลา เป็น วินาที ใช้เป็นนาทีต้อง * 60
        items = {
            item = { -- ของที่ได้แน่ๆ

                {
                    chance = 100, -- โอกาสได้ จาก MaxChance
                    name = 'money', -- ไอเท็มที่จะได้
                    count = 5000, -- จำนวน
                },
                {
                    chance = 100,
                    name = 'up1', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 100,
                    name = 'UpSideCard', -- ไอเท็มที่จะได้
                    count = 15, -- จำนวน
                },
            },
            --luckyItem = { -- ของ ที่มีโอกาสได้จาก lucky
            --    {
            --                 chance = 0, -- โอกาสที่จะได้
            --                 name = 'AFK_Card', -- ไอเท็มที่จะได้
            --                 count = 1, -- จำนวน
            --    },
            --},
        },
    },
    AFK_Card1 = -- ชื่อไอเท็มที่เอาไว้กดใช้ ห้ามซ้ำ
    {
        timer =  1800, -- ระยะเวลา เป็น วินาที ใช้เป็นนาทีต้อง * 60
        items = {
            item = { -- ของที่ได้แน่ๆ

                {
                    chance = 100, -- โอกาสได้ จาก MaxChance
                    name = 'money', -- ไอเท็มที่จะได้
                    count = 5000, -- จำนวน
                },
                {
                    chance = 100,
                    name = 'up1', -- ไอเท็มที่จะได้
                    count = 1, -- จำนวน
                },
                {
                    chance = 100,
                    name = 'UpSideCard', -- ไอเท็มที่จะได้
                    count = 15, -- จำนวน
                },
            },
            --luckyItem = { -- ของ ที่มีโอกาสได้จาก lucky
            --    {
            --                 chance = 0, -- โอกาสที่จะได้
            --                 name = 'AFK_Card', -- ไอเท็มที่จะได้
            --                 count = 1, -- จำนวน
            --    },
            --},
        },
    },
} 