---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Blugthek.
--- DateTime: 9/3/2022 5:51 PM
---
local isReady = false
local currentScriptName = GetCurrentResourceName()
local markerList = {}

AddEventHandler('onResourceStart', function(resourceName)
    if (GetCurrentResourceName() ~= resourceName) then
        return
    end
    Citizen.Wait(1000)
    print()
    print('The resource ' .. resourceName .. ' has been started.')
    print('Custom script BY BLUGTHEK')
    print()
end)

AddEventHandler('esx:playerLoaded', function(source)
    local source_ = source
    TriggerClientEvent(currentScriptName..':client:updateMarker',source_,markerList)
end)

AddEventHandler('bx:getBlackListed', function(cb)
    cb(Config['itemList'])
end)

Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent("esx:getSharedObject", function(obj)
            ESX = obj
        end)
        Citizen.Wait(0)
    end

    isReady = true

    if isReady then
        for k,v in pairs(Config['itemList']) do
            ESX.RegisterUsableItem(k, function(source)
                local _source = source
                local xPlayer = ESX.GetPlayerFromId(_source)
                if xPlayer then
                    if xPlayer.getInventoryItem(k).count > 0 then
                        TriggerClientEvent(currentScriptName..':useAfkItem', source,k, v)
                    else
                        TriggerClientEvent('blug_ext:SendNotification',source,{
                            title = 'ไม่สามารถทำได้',
                            description = 'คุณไม่มีไอเทมที่ต้องใช้ : '..k,
                            type = 'error'
                        })
                    end
                end
            end)
        end
    end

    ESX.RegisterServerCallback(currentScriptName..':checkInitialized',function(_, cb)
        cb(isReady)
    end)
end)

RegisterServerEvent(currentScriptName .. ':server:addItem')
AddEventHandler(currentScriptName .. ':server:addItem', function(data)
    local _source = source;
    local xPlayer = ESX.GetPlayerFromId(_source)
    
    local tItem = data['item']
    local lItem = data['luckyItem']

    for k,v in pairs(tItem) do
        local chance = math.random(Config['maxChance'])
        local secondChance = math.random(Config['maxChance'])
        if secondChance > chance then
            chance = secondChance
        end
        if v.chance >= chance then
            if v.name == 'money' then
                xPlayer.addMoney(v.count)
            else
                xPlayer.addInventoryItem(v.name, v.count)
            end
        end
    end

    if lItem ~= nil and type(lItem) == 'table' then
        for k,v in pairs(lItem) do
            local chance = math.random(Config['maxChance'])
            local secondChance = math.random(chance,Config['maxChance'])
            chance = secondChance
            if v.chance >= chance then
                if v.name == 'money' then
                    xPlayer.addMoney(v.count)
                else
                    xPlayer.addInventoryItem(v.name, v.count)
                end
            end
        end        
    end    
end)

RegisterServerEvent(currentScriptName..':server:addMarker')
AddEventHandler(currentScriptName..':server:addMarker', function()
    local source_ = source
    markerList[source_] = true
    TriggerClientEvent(currentScriptName..':client:updateMarker',-1,markerList)
end)

RegisterServerEvent(currentScriptName..':server:removeMarker')
AddEventHandler(currentScriptName..':server:removeMarker', function()
    local source_ = source
    markerList[source_] = false
    Citizen.Wait(300)
    TriggerClientEvent(currentScriptName..':client:updateMarker',-1,markerList)
end)